version: '3.7'

services:

  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - WATCHPACK_POOLING=true
    command: npm start